### ISSUE TITLE
FEATURE - Persist theme option in localstorage or cookie

### ISSUE THREAD

**Issue by brunoruas2** [FernandoCelmer/mkdocs-simple-blog#31]
I think it would be a cool feature to persist the theme selection in local browser data, to pass this information to all pages, not just the current selection, as a default feature of mkdocks-simple-blog.

Where do you think is the most appropriate place to persist this information? LocalStorage or some cookie usage?

**Comment by FernandoCelmer** [comment]
Interesting question @brunoruas2. So, analyzing it, I believe that `localstorage` should be the way to go, because it is the best way to persist this type of configuration compared to `cookies`.

For `mkdocs-simple-blog` there is already an option to configure the theme that will be rendered. This configuration is in the `mkdocs.yml` file, and you can change the theme type or colors separately.

Example:

```yml
theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
```
![2023-12-04_20-39](https://github.com/FernandoCelmer/mkdocs-simple-blog/assets/6262214/3639db9e-3756-4d9d-b80f-9bf97fa05ded)

Links:
- [Mkdocs Simple Blog - Documentation Colors](https://fernandocelmer.github.io/mkdocs-simple-blog/nav/setup/colors/)
-  [Should I use localstorage when changing a theme?](https://stackoverflow.com/questions/65845400/react-should-i-use-localstorage-when-changing-a-theme)
